### ISSUE TITLE
Package Control?

### ISSUE THREAD

**Issue by mAAdhaTTah** [gerardroche/sublime-php-grammar#1]
Is this available in Package Control? If not, can you add?

**Comment by gerardroche** [comment]
I think maybe there needs to be a few more 0.x releases before adding to Package Control (if it will be accepted).

**Comment by gregrobson** [comment]
:+1: for package control. That would be the icing on the cake.

(it's great btw, I'm writing lots of code with arrays at the moment!)

**Comment by gerardroche** [comment]
@gregrobson Thanks. I've added two new macros you might like, one specifically for arrays. Their in the develop branch. See https://github.com/gerardroche/sublime-php-grammar/tree/develop#macros.

**Comment by gregrobson** [comment]
@gerardroche Thanks - I'll update my local copy, every keystroke saved helps :smile:

**Comment by gerardroche** [comment]
@gregrobson Just pushed a fix for that in the develop branch. Thanks.

**Comment by gregrobson** [comment]
:+1:
