### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by devWaleed** [gerardroche/sublime-php-grammar#101]
I installed your plugin, it wasn't what I was looking for and now my whole sublime PHP syntax has got corrupted. I removed and reinstalled SublimeText 3 but still. No code completion, no syntax highlighting, suggestion or colorful syntax.

Please help.

**Comment by gerardroche** [comment]
Read the [Installation section in the readme](https://github.com/gerardroche/sublime-php-grammar#installation) about disabling or uninstalling php-grammar.
