### ISSUE TITLE
Many themes highlight parens improperly using this grammar

### ISSUE THREAD

**Issue by adamwathan** [gerardroche/sublime-php-grammar#103]
Not sure what the solution is here, but when I use this PHP grammar, a lot of themes don't highlight matching parentheses correctly.

Here's an example using the [material theme](https://github.com/equinusocio/material-theme):

![image](https://cloud.githubusercontent.com/assets/4323180/22509598/c765708a-e85c-11e6-8372-dc7cfdb9e1ee.png)

Thanks!

**Comment by gerardroche** [comment]
Re: #104 next version uses default package syntax.
