### ISSUE TITLE
Question about new version

### ISSUE THREAD

**Issue by Mosquito13** [gerardroche/sublime-php-grammar#105]
Why did you remove the tmLanguage file?

I ask because I have a color scheme based on php-grammar scopes.

**Comment by gerardroche** [comment]
I'm afraid it just wasn't worth maintaining. The native PHP package and php-grammar diverged a lot and packages like [PHPUnitKit](https://github.com/gerardroche/sublime-phpunit), [PHP Completions Kit](https://github.com/gerardroche/sublime-phpck), [php-snippets](https://github.com/gerardroche/sublime-php-snippets), PHPUnit Completions, aswell as many more including colors schemes, they depend on a php syntax, and so are faced with either supporting the native package syntax, the php grammar syntax, or both, and it's too much time to support both.

**Comment by Mosquito13** [comment]
In this point of view, I agree with you. Thanks for the anwser!
