### ISSUE TITLE
Parentheses and square brackets no longer indent correctly

### ISSUE THREAD

**Issue by svivian** [gerardroche/sublime-php-grammar#106]
When I press enter between square brackets or parentheses, Sublime no longer indents the cursor. Curly braces are fine, I get the indented cursor. Examples, with `|` as the cursor:

    $x = [|]
    // or
    $x = array(|)

Pressing Enter there gives me this result:

    $x = [
    |]
    // or
    $x = array(
    |)

Previously, I got this result:

    $x = [
        |
    ]
    // or
    $x = array(
        |
    )

I also seem to recall the semicolon was automatically inserted as well as the `]` when typing `[`

I've just noticed this issue happening in the past week or two, and it seems this plugin was updated a couple of weeks ago. So presumably it's a regression due to this?

**Comment by gerardroche** [comment]
What version of Sublime Text are you on? And what OS?

**Comment by svivian** [comment]
Sublime Text 3.0 Build 3143
Mac OSX High Sierra 10.13.3

Plugins all up to date.

**Comment by gerardroche** [comment]
Looks like it might be related to 


Can you try enabling debug logs and see what if the correct macros are being triggered?

In the console (Menu > View > Show Console) run: sublime.log_commands(True); sublime.log_input(True).

It should show something like:

```
>>> sublime.log_commands(True); sublime.log_input(True)
chr evt: $ (0x24)
chr evt: x (0x78)
chr evt:   (0x20)
chr evt: = (0x3d)
chr evt:   (0x20)
chr evt: [ (0x5b)
command: insert_snippet {"contents": "[$0];"}
key evt: enter
command: run_macro_file {"file": "res://Packages/PHPGrammar/macros/wrap-newlines.sublime-macro"}
```

**Comment by svivian** [comment]
Here's what I get, seems to be missing the macro part.

```
>>> sublime.log_commands(True)
>>> sublime.log_input(True)
command: drag_select {"event": {"button": 1, "x": 300.19921875, "y": 124.94140625}}
chr evt: $ (0x24)
chr evt: x (0x78)
chr evt:   (0x20)
chr evt: = (0x3d)
chr evt:   (0x20)
chr evt: [ (0x5b)
command: insert_snippet {"contents": "[$0]"}
key evt: enter
command: insert {"characters": "\n"}
```

I checked "Browse Packages" like you mention in #107 but I don't have any PHPGrammar folder in there.

**Comment by svivian** [comment]
PHPGrammar is definitely installed. I checked the "Installed Packages" folder and the `PHPGrammar.sublime-package` file is there. But no PHPGrammar under Packages.

I added that binding as detailed and now nothing happens when I press Enter. There is a message on the status bar "Unable to open res://Packages/PHPGrammar/macros/wrap-newlines.sublime-macro". As I said there is no PHPGrammar folder under Browse packages.

I'm not 100% sure what you mean by scope but pressing Cmd+Alt+P on Mac shows a small popup with this:

	embedding.php
	text.html.basic
	meta.embedded.block.php
	source.php
	meta.class.php
	meta.block.php
	meta.array.empty.php
	punctuation.section.array.end.php

**Comment by svivian** [comment]
OK I just tried removing PHPGrammar, restarting Sublime, then reinstalling the package. And now it works!! Don't know why because I'd already tried doing that before I reported the but in the first place. Maybe something with the previous version of ST I dunno. Anyway thanks for the help!

**Comment by gerardroche** [comment]
The scope is what the macro uses to match *when* it should be active (the context selector key in the macro definition is what matches). Yours was working fine so that wasn't the issue.

It looks like either there was a bug in ST that was fixed (did you update recently, and from what versions?), or somehow the `PHPGrammar.sublime-package` that you had installed was missing the macro. That can happen for example when users modify packages with plugins like [PackageResourceViewer](https://packagecontrol.io/packages/PackageResourceViewer): this package allows users to modify sublime-packages in place, but sounds like you don't use anything like that.

**Comment by svivian** [comment]
No I hadn't modified any packages. I recently updated to ST Build 3170 from whatever I had before (3143 as above most likely).
