### ISSUE TITLE
Enter inside of empty array brackets causes incorrect indentation

### ISSUE THREAD

**Issue by adamwathan** [gerardroche/sublime-php-grammar#107]
Given this:

```php
class Foo
{
    protected $bar = [|];
}
```

...hitting enter is giving me this:

```php
class Foo
{
    protected $bar = [
        |
];
}
```

Happy to help troubleshoot if someone can point me in the right direction; haven't worked on a project like this before!

**Comment by gerardroche** [comment]
I'm not able to reproduce the issue, I've tested against ST builds 3164 and 3143. 

What version of ST and PHPGrammar are you using?

Try enabling debug logs: 

In the console (`Menu > View > Show Console`) run: `sublime.log_commands(True); sublime.log_input(True)`.

It should give you logs something like:

```
>>> sublime.log_commands(True); sublime.log_input(True)
chr evt: c (0x63)
chr evt: l (0x6c)
chr evt: a (0x61)
chr evt: s (0x73)
chr evt: s (0x73)
chr evt:   (0x20)
chr evt: F (0x46)
chr evt: o (0x6f)
chr evt: o (0x6f)
key evt: enter
command: insert {"characters": "\n"}
chr evt: { (0x7b)
command: insert_snippet {"contents": "{$0}"}
key evt: enter
command: run_macro_file {"file": "res://Packages/Default/Add Line in Braces.sublime-macro"}
chr evt: p (0x70)
chr evt: r (0x72)
chr evt: o (0x6f)
chr evt: t (0x74)
chr evt: e (0x65)
chr evt: c (0x63)
chr evt: t (0x74)
chr evt: e (0x65)
chr evt: d (0x64)
chr evt:   (0x20)
chr evt: $ (0x24)
chr evt: v (0x76)
chr evt: a (0x61)
chr evt: r (0x72)
chr evt:   (0x20)
chr evt: = (0x3d)
chr evt:   (0x20)
chr evt: [ (0x5b)
command: insert_snippet {"contents": "[$0];"}
key evt: enter
command: run_macro_file {"file": "res://Packages/PHPGrammar/macros/wrap-newlines.sublime-macro"}
```

**Comment by adamwathan** [comment]
Hey @gerardroche thanks for looking at this for me!

This is what I see in the log after adding an empty array and pressing enter inside of it:

```
command: insert_snippet {"contents": "[$0];"}
key evt: enter
command: run_macro_file {"file": "res://Packages/PHPGrammar/macros/wrap-newlines.sublime-macro"}
```

I realized I'm actually seeing this behavior with PHP Grammar disabled too though, so gonna close this since it must be something else causing it. Still pulling my hair out regardless 😅

**Comment by gerardroche** [comment]
If it's still running with PHPGrammar disabled then maybe at some point you customised that macro. 

Check your User directory: `Preferences > Browse Packages`. If the macro is customised then it should be located at `User/PHPGrammar/macros/macros/wrap-newlines.sublime-macro`. If it's there delete it.

Check your keymaps, `Preferfences > Key Bindings`. Look for any keymaps that might be using the wrap-newlines macro.

**Comment by gerardroche** [comment]
You can also try the macro directly to see if that will work. Add this key binding:

```
    {
        "keys": ["enter"],
        "command": "run_macro_file",
        "args": {"file": "res://Packages/PHPGrammar/macros/wrap-newlines.sublime-macro"},
        "context": [
            { "key": "setting.command_mode", "operand": false },
            { "key": "setting.auto_indent", "operator": "equal", "operand": true },
            { "key": "selector", "operator": "equal", "operand": "source.php meta.array.empty", "match_all": true },
            { "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true }
        ]
    },
```
