### ISSUE TITLE
Consider contributing to official packages

### ISSUE THREAD

**Issue by kurtextrem** [gerardroche/sublime-php-grammar#15]
https://github.com/sublimehq/Packages
Not everything from php-grammar goes there, but for example the syntax is a great start. Oh, also: https://github.com/sublimehq/Packages/pull/22. Maybe you two could work together to ultimately improve the official package? @jobedom

**Comment by gerardroche** [comment]
There are several open issues:

- Splitting packages into individual repositories. http://www.sublimetext.com/forum/viewtopic.php?f=2&t=18787
- [Specify patterns to ignore certain files in a certain package](https://github.com/SublimeTextIssues/Core/issues/901) e.g. snippets https://github.com/sublimehq/Packages/issues/8
