### ISSUE TITLE
Third-party syntaxes, "source.php" scope not working

### ISSUE THREAD

**Issue by anlutro** [gerardroche/sublime-php-grammar#21]
[A package I'm using for laravel blade template syntax highlighting](https://github.com/Medalink/laravel-blade) uses `- include: 'scope:source.php'` to achieve PHP syntax highlighting where appropriate. This works fine with the default PHP syntax definition, not so much with this package.

I see that the default PHP syntax is split into two files - one for the "embedding.php" scope, and one for the "source.php" scope. The embedding one is the one actually used for files, and it includes the "source.php" one, but also allows other syntax definitions to include the "source.php" scope without importing the full embedded HTML syntax.

Is this approach something this package could adopt? It would fix compatibility with the blade package and possibly others that build on top of the "source.php" scope.

https://github.com/sublimehq/Packages/blob/master/PHP/PHP.sublime-syntax
https://github.com/sublimehq/Packages/blob/master/PHP/PHP%20Source.sublime-syntax

**Comment by gerardroche** [comment]
Makes sense. I'll patch it later today.

**Comment by gerardroche** [comment]
Taking a look this now.

When I add a PHP Source file like teh default package then the html in blade templates doesn't highlight correctly does it?

Example

```
<!-- Stored in app/views/layouts/master.blade.php -->

<html>
    <body>
        @section('sidebar')
            This is the master sidebar.
        @show

        <div class="container">
            @yield('content')
        </div>
        <?php
        echo 'hello';
        ?>
    </body>
</html>
```

**Comment by anlutro** [comment]
The blade package pushes the HTML scope at the beginning:

```yml
contexts:
  main:
    - match: ''
      push: 'scope:text.html.basic'
```

So it shouldn't matter what this package does, as long as the `source.php` scope is present.

Make sure you use the recent version of the blade package - the syntax definition was only just updated to support recent builds of ST3.

**Comment by gerardroche** [comment]
I needed the latest version of the blade package. Thanks. :+1:
