### ISSUE TITLE
Re-enable PHP in uninstall hook

### ISSUE THREAD

**Issue by rudiedirkx** [gerardroche/sublime-php-grammar#24]
If there is an uninstall hook/event/trigger, this package should re-enable PHP. I've no idea if it's possible.

**Comment by gerardroche** [comment]
Package control has events for this very purpose. https://packagecontrol.io/docs/events

Will take a look when I get a chance, will accept an pr too.

**Comment by rudiedirkx** [comment]
I might give it a go Friday, but don't hold your breath.

**Comment by mathroc** [comment]
:+1:

**Comment by gerardroche** [comment]
re: https://github.com/SublimeText-Markdown/MarkdownEditing/issues/284
