### ISSUE TITLE
autocomplete conflict

### ISSUE THREAD

**Issue by thik** [gerardroche/sublime-php-grammar#25]
<kbd>Enter</kbd>

    ```php
    $val = array(               | $val = array(
        'str|'                  |     'str',
    )                           |     |
                                | )
    ```
this should use <kbd>Ctrl + Enter</kbd> instead because when typing 'string' if has an autocomplete popup visible, press <kbd>Enter</kbd> should select autocomplete value instead of run the macro.

**Comment by gerardroche** [comment]
:+1:
