### ISSUE TITLE
HTML has no effect by color scheme

### ISSUE THREAD

**Issue by quocvuongdn** [gerardroche/sublime-php-grammar#3]
My HTML code has no effect by color scheme when i ignored PHP package in sublime-setting. How to resolved it?

Thanks!

**Comment by quocvuongdn** [comment]
Sorry, i think it's not this package problem.

**Comment by gerardroche** [comment]
Sublime Text Version? System, windows, linux? Can you show the html in question. and what the file name and extension is.

**Comment by gerardroche** [comment]
For cleaning out caches and optionally any sessions https://gist.github.com/gerardroche/6e46cbdf8da19a39f9da

**Comment by quocvuongdn** [comment]
I did try the same as your guide, but nothing changes.
I'm using Sublime Text 3, Windows. File name is name.php, it's a CodeIgniter view class.
![htmlisntformattedbycolorscheme](https://cloud.githubusercontent.com/assets/3168632/5803446/2b3c4c4e-a031-11e4-88b0-212ff093c1d0.png)

P/s: I installed Emmet before sublime-php-grammar, it's works fine for a long time. But, now Emmet only run on .html file, not work for .php file.

**Comment by gerardroche** [comment]
Sorry i'm not understanding what exactly is not working. The color scheme is working, but the emmet plugin stops working for php files?

**Comment by quocvuongdn** [comment]
Color scheme is not work for HTML, PHP is normal (but HTML and PHP in once file). When i capture my code and upload to this topic, i did try Emmet... and it's not work too. If I remove ignore-package "PHP", all things returned to normal.

**Comment by gerardroche** [comment]
Ok, i see, I'm sure I can fix this. Emmet is not the issue. Sublime Text is doing something internally. 

The long explaination.

File types like `.phtml` with html work as expected but html in `.php` files are not recognosed properly. There is a comment at the top of the PHP syntax definition:

	<key>fileTypes</key>
	<array>
		
		<string>php</string>
	</array>

I deleted the default PHP package from the Sublime Text installation completely and copied the php-grammar package into a directory named PHP in the User directory and viola it works!.  Renaming the directory to php-grammar or anything else causes the issue again. 

Sublime is opening `.php` files as HTML specifically for a package with directory name PHP and making it look like the file opened with the PHP syntax definition. I'm not sure how to fix this.

**Comment by quocvuongdn** [comment]
I did try and successful by your guide. Thanks again!
