### ISSUE TITLE
PHP "double-slash" comments are not indented. And breaks further indentation.

### ISSUE THREAD

**Issue by arnisjuraga** [gerardroche/sublime-php-grammar#33]
Hi!

I have search in issues, but did not find anything similar, please correct me if I'm wrong:

At first, guys, Great plugin! Works great and does 'almost' all I have needed.
Except.

If I have one comment line in PHP, starting with "//", it will not be indented, but will start from first column:

``` php
<?php
class Product extends Controller {
    private $error = array();
    public function indentationTest() {
// This is comment line, 
    // both lines must start at column 3 after indentation!
        echo "test";
    }
}
```

And also - if the "//" comment line starts at the end of PHP line, then indentation from the next line start at column 1:

``` php
<?php
class Product extends Controller {
    private $error = array();
public function indentationTest() { // This is comment and breaks THIS line and everything further
// now this and all other lines must still start
// at column 3 ! But they don't.
    echo "test";
}
}
```

Is this a bug or is this a Feature?

**Comment by gerardroche** [comment]
It's not a feature but it's not exactly a bug either. Currently any line with a comment or any line ending in a comment is ignored by the indentation rules. It's not straight forward to solve either.

The easiest solution will be to have indentation rules always indent comment lines like below as per your examples.

```php
class Product extends Controller {
    private $error = array();
    public function indentationTest() {
        // This is comment line, 
        // both lines must start at column 3 after indentation!
        echo "test";
    }
}

class Product extends Controller {
    private $error = array();
    public function indentationTest() { // This is comment and breaks THIS line and everything further
        // now this and all other lines must still start
        // at column 3 ! But they don't.
        echo "test";
    }
}
```

**Comment by arnisjuraga** [comment]
It is still an issue. If I want to re-indent PHP code with comment lines, the result is not predictable.
Is there any solution? E.g. - turn off php-grammar indentation and use other module?

**Comment by gerardroche** [comment]
I'm afraid yes this is still an issue. I don't know of any sublime plugins that solve it but I'm sure there are a few html tidy plugins.

As a standalone, the [PHP Coding Standards Fixer](http://cs.sensiolabs.org/) is very good. There's probably a sublime plugin for it too but I don't use one myself.
