### ISSUE TITLE
Add smart array ` => ` macro completion

### ISSUE THREAD

**Issue by gerardroche** [gerardroche/sublime-php-grammar#41]
Pressing tab at:

```
$x = array(
    'str'|           
);                  
```

Should complete as:

```
$x = array(
    'str' => |
);
```

**Comment by arnisjuraga** [comment]
Nice, this is one of my wishes, to have in any macros tool. 
Is it considerable to add pressing tab also inside quotes?

    $x = array(
        'str|'
    );  


would complete as 

    $x = array(
        'str' => |
    );
