### ISSUE TITLE
PHP Syntax disappeared after uninstall

### ISSUE THREAD

**Issue by MalcolmK** [gerardroche/sublime-php-grammar#43]
After I uninstalled the php grammar plugin, my PHP syntax completely disappeared. I tried to close all files. Reopened sublime. Nothing seems to help. When I take a look in the list of syntaxes, the PHP syntax is missing. 

I'm using Mac OS X, ST3 build 3083.

**Comment by MalcolmK** [comment]
I fixed it myself. I removed "PHP" from the ignored packages and restarted sublime.

**Comment by gerardroche** [comment]
Yes you need to manually reenable the native PHP package, https://github.com/gerardroche/sublime-php-grammar#package-control-installation.

Re: https://github.com/gerardroche/sublime-php-grammar/issues/24
