### ISSUE TITLE
Tab no working

### ISSUE THREAD

**Issue by iLenTheme** [gerardroche/sublime-php-grammar#44]
Hi, when I put the following does not work

``` php
$g = array(
                'sdfdofokosdf',
                'hola',
                "hola(PRESS TAB)"

            )
             ?>
```

The result should be

``` php
$g = array(
                'sdfdofokosdf',
                'hola',
                "hola" => 

            )
             ?>
```

but it does not work, it can be happening?

**Comment by gerardroche** [comment]
It works in ST 3095 on Ubuntu for me. What version of ST are using and what OS?

**Comment by iLenTheme** [comment]
Window 10 with Sublime Text 3.
Another question, this plugin is compatible with Material Theme ?, because every time you install the .php or .html files cease to paint colors. The colors meclan or confused, it is strange but I tried it several times.

My plugins:
Material Theme
Better Completion
AndyPHP

**Comment by gerardroche** [comment]
Try closing all the php files, restarting, now opening the files will be ok. This is an Sublime Text issue. It can't be fixed by php-grammer. https://github.com/gerardroche/sublime-php-grammar/issues/9#issuecomment-108865807

What build are you using? `Menu > About > Help` Try using build 3095 https://github.com/gerardroche/sublime-php-grammar/issues/9#issuecomment-153515464

**Comment by gerardroche** [comment]
Also, can you tell me if you installed via Package Control or did you install manually via a git clone. Thanks.

**Comment by gerardroche** [comment]
Can you confirm if this is fixed in the latest Sublime Text beta. As of writing the latest build is 3103, https://www.sublimetext.com/3. 

There are also dev builds, as of writing the latest dev build is 3105 https://www.sublimetext.com/3dev.

**Comment by gerardroche** [comment]
The cursor needs to be at the end of the string.

For example instead of:

```
$g = array(
                'sdfdofokosdf',
                'hola',
                "hola(PRESS TAB)"

            )
             ?>
```

Do

```
$g = array(
                'sdfdofokosdf',
                'hola',
                "hola()PRESS TAB"

            )
             ?>
```
