### ISSUE TITLE
Error loading syntax file dialog

### ISSUE THREAD

**Issue by gerardroche** [gerardroche/sublime-php-grammar#45]
When installing php-grammar sometimes an error dialog pops up with "Error loading syntax file".

```
Error loading syntax file "Packages/HTML/HTML.tmLanguage": Unable to open Packages/PHP/PHP.tmLanguage
```
```
Error loading syntax file "Packages/php-grammar/PHP.sublime-syntax": Unable to read Packages/php-grammar/PHP.sublime-syntax
```

To resolve this, close any opened php files. Once closed reopening them will have the new installed syntax applied and there will be no more error dialogs.

The reason this happens is because ST caches the syntax definition applied to the opened views. When the new syntax is installed it is not automatically applied to opened views by ST.

When opening other workspaces that had the old syntax applied, if the workspace starts with opened files there may be the error dialog again. Closing the open files will resolve it.

This only needs to be done once on install if there open php files when php-grammar is installed and once for workspaces created before installing php-grammar and that start with opened files.

re: https://github.com/gerardroche/sublime-php-grammar/issues/9#issuecomment-108899819

**Comment by gerardroche** [comment]
re: https://github.com/SublimeText-Markdown/MarkdownEditing/issues/205

**Comment by iLenTheme** [comment]
if corrected ;)
