### ISSUE TITLE
Should the current version be tagged 1.0.0 and make v2 support PHP 7 

### ISSUE THREAD

**Issue by gerardroche** [gerardroche/sublime-php-grammar#84]
PHP 7 Features: https://github.com/gerardroche/sublime-php-grammar/labels/php7

**Comment by joshdifabio** [comment]
Are you likely to have any time to work on the PHP 7 features?

**Comment by gerardroche** [comment]
I haven't been lucky enough to use php 7 yet. That said, I've updated the [php completion package](https://packagecontrol.io/packages/PHP%20Completions%20Kit) to php 7 and expect to update this grammar soon enough.

**Comment by joshdifabio** [comment]
Brilliant, thanks.

**Comment by gerardroche** [comment]
I decided to just continue with the 0.x.x versioning and have also created a `5.x` branch for what is now the old php 5.6 only grammar.

PHP 7 roadmap https://github.com/gerardroche/sublime-php-grammar/issues/91
