### ISSUE TITLE
Conflicts to "indent_to_bracket" option.

### ISSUE THREAD

**Issue by ptcong** [gerardroche/sublime-php-grammar#90]
Hello,
Thank you for the package, but i just found an issue that this package conflict with "indent_to_bracket" option.
When i use this package with indent_to_bracket, ST3 will not indent new line to bracket and even not indent anything, just first postiion in new line.

**Comment by gerardroche** [comment]
```
    // Adds whitespace up to the first open bracket when indenting. Requires
    // auto_indent to be enabled.
    "indent_to_bracket": false,
```

**Comment by ptcong** [comment]
`auto_indent` is true by default,

sometimes i want to ident to bracket instead of normal behavior.
`"indent_to_bracket": true`

I'm using ST3 build 3111, Mac OS
