### ISSUE TITLE
Incorrect indentation for multi-line (>2) text strings

### ISSUE THREAD

**Issue by arnisjuraga** [gerardroche/sublime-php-grammar#94]
Code:

``` php
<?php

if( 2 > 1 ) {
    $message .= "aaa
bbb
ccc";
}
```

Expected result:

``` php
<?php

if( 2 > 1 ) {
    $message .= "aaa
    bbb
    ccc";
}
```

Actual result: **the same as Code**

Although, if I have only 2 lines of string, then indentation works:

Code:

``` php
<?php

if( 2 > 1 ) {
    $message .= "aaa
ccc";
}
```

Result:
Code:

``` php
<?php

if( 2 > 1 ) {
    $message .= "aaa
    ccc";
}
```

**Comment by joshdifabio** [comment]
I don't think it'd be correct to indent the string as you have suggested, because doing so would actually change the string (i.e. by adding spaces to it). I think indentation should always be semantically neutral.

**Comment by arnisjuraga** [comment]
Then, it's not consistent:

It's indenting 2 lines (text with one newline) but not more.

Could be configurable?

**Comment by joshdifabio** [comment]
Indentation features should never actually change the meaning of the code. If you try doing this in PHPStorm you'll see that it won't indent the string as you are suggesting. 

The following two pieces of code are not equivalent:

```php
$foo = 'bar
baz';
```

```php
$foo = 'bar
    baz';
```

**Comment by arnisjuraga** [comment]
And more - I can't check it now, but next code line after string variable, should be indented at the same level as "$message"
